export enum WASTE_CODES_LABELS {
    BASEL_ANNEX_IX = 'Basel Annex IX',
    OECD = 'OCED',
    ANNEX_IIIA = 'Annex IIIA',
    ANNEX_IIIB = 'Annex IIIB',
}

// Basel Annex IX autocomplete
export const baselAnnexIX = [
    'B1010: Metal and metal-alloy wastes in metallic, non-dispersible form',
    'B1020: Clean, uncontaminated metal scrap, including alloys, in bulk finished form',
    'B1030: Refractory metals containing residues',
    'B1031: Molybdenum, tungsten, titanium, tantalum, niobium and rhenium metal and metal alloy',
    'B1040: Scrap assemblies from electrical power generation not contaminated with lubricating oil',
    'B1050: Mixed non-ferrous metal, heavy fraction scrap',
    'B1060: Waste Selenium and Tellurium in metallic elemental form including powder',
    'B1070: Waste of copper and copper alloys in dispersible form',
    'B1080: Zinc ash and residues including zinc alloys residues in dispersible form',
    'B1090: Waste batteries conforming to a specification, excluding those made with lead, cadmium or mercury',
    'B1100: Metal-bearing wastes arising from melting, smelting and refining of metals:',
    'B1115: Waste metal cables coated or insulated with plastics',
    'B1120: Spent catalysts excluding liquids used as catalysts',
    'B1130: Cleaned spent precious-metal-bearing catalysts',
    'B1140: Precious-metal-bearing residues in solid form which contain traces of inorganic cyanides',
    'B1150: Precious metals and alloy wastes (gold, silver, the platinum group, but not mercury) ',
    'B1160: Precious-metal ash from the incineration of printed circuit boards ',
    'B1170: Precious-metal ash from the incineration of photographic film',
    'B1180: Waste photographic film containing silver halides and metallic silver',
    'B1190: Waste photographic paper containing silver halides and metallic silver',
    'B1200: Granulated slag arising from the manufacture of iron and steel',
    'B1210: Slag arising from the manufacture of iron and steel ',
    'B1220: Slag from zinc production, chemically stabilised, having a high iron content (above 20 %)',
    'B1230: Mill scaling arising from the manufacture of iron and steel',
    'B1240: Copper oxide mill-scale',
    'B1250: Waste end-of-life motor vehicles',
    'B2010: Wastes from mining operations in non-dispersible form',
    'B2020: Glass waste in non-dispersible form',
    'B2030: Ceramic wastes in non-dispersible form',
    'B2040: Other wastes containing principally inorganic constituents',
    'B2060: Spent activated carbon ',
    'B2070: Calcium fluoride sludge',
    'B2080: Waste gypsum arising from chemical industry processes ',
    'B2090: Waste anode butts from steel or aluminium production made of petroleum coke or bitumen',
    'B2100: Waste hydrates of aluminium and waste alumina and residues from alumina production',
    'B2110: Bauxite residue (red mud) (pH moderated to less than 11,5)',
    'B2120: Waste acidic or basic solutions with a pH greater than 2 and less than 11,5',
    'B2130: Bituminous material (asphalt waste) from road construction and maintenance',
    'B3011: Plastics (shipped outside EU) provided it is destined for recycling/reclamation in an environmentally sound manner and almost free from contamination and other types of wastes',
    'EU3011: Plastics (shipped within EU) provided it is almost free from contamination and other types of waste',
    'B3020: Paper, paperboard and paper product wastes',
    'B3026: Non-seperable plastic fraction or non-separable plastic-aluminium fraction waste from the pre-treatment of used liquid packages',
    'B3027: Self-adhesive label laminate waste containing raw materials used in label material production',
    'B3030: Textile wastes',
    'B3035: Waste textile floor coverings, carpets',
    'B3040: Rubber wastes',
    'B3050: Untreated cork and wood waste',
    'B3060: Wastes arising from agro-food industries provided it is not infectious',
    'B3065: Waste edible fats and oils of animal or vegetable origin (e.g. frying oils)',
    'B3070: The following wastes: Human Hair, Straw, Deacticated fungus mycelium from penicillin production to be used as animal feed',
    'B3080: Waste parings and scrap of rubber',
    'B3090: Paring and other wastes of leather or of composition leather',
    'B3100: Leather dust, ash, sludges or flours not containing hexavalent chromium compounds',
    'B3110: Fellmongery wastes not containing hexavalent chromium compounds',
    'B3120: Wastes consisting of food dyes',
    'B3130: Waste polymer ethers and waste non-hazardous monomer ethers',
    'B3140: Waste pneumatic tyres, excluding those destined for Annex IVA operations',
    'B4010: Wastes consisting mainly of water-based/latex paints, inks and hardened varnishes not',
    'B4020: Wastes from production, formulation and use of resins, latex, plasticisers',
    'B4030: Used single use cameras, with batteries not included on list A'
  ]